---
- hosts: control
  become: true
  tasks:
    - name: Update /etc/hostname file
      action: lineinfile dest=/etc/hostname regexp=.* line={{inventory_hostname}} create=yes

    - name: set hostname to current ansible name
      action: command hostname {{inventory_hostname}}

    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - curl
